import type { CodegenConfig } from "@graphql-codegen/cli";

const CMS_SPACE = process.env.CMS_SPACE ?? "";
const CMS_PROD_TOKEN = process.env.CMS_PROD_TOKEN ?? "";
const CMS_ENV = process.env.CMS_ENV ?? "master";

const config: CodegenConfig = {
  schema: [
    {
      [`https://graphql.contentful.com/content/v1/spaces/${CMS_SPACE}/environments/${CMS_ENV}`]:
        {
          headers: {
            Authorization: `Bearer ${CMS_PROD_TOKEN}`,
          },
        },
    },
  ],
  ignoreNoDocuments: true,
  documents: ["src/**/*.ts", "!node_modules"],
  generates: {
    "src/graphql/generated/cms.generated.ts": {
      config: {
        avoidOptionals: true,
      },
      plugins: [
        {
          add: {
            content: `// DO NOT EDIT
// This file is automatically generated, run yarn gen to update
        `,
          },
        },
        "typescript",
        "typescript-operations",
        "typescript-graphql-request",
      ],
    },
    "./schema.generated.graphql": {
      plugins: ["schema-ast"],
    },
  },
};
export default config;
